"""Render a compiled Docatoms document without external dependencies."""

from __future__ import annotations

import re
from collections.abc import Iterator

from .core import Atom, Document

_INLINE_RE = re.compile(r"`([^`\n]+)`|(?<!\*)\*([^*\n]+)\*(?!\*)")


def _markdown_atom(atom: Atom, level: int) -> list[str]:
    if atom.kind == "tool":
        lines = [f"# {atom.title}", "", f"> {atom.short_help}"]
    else:
        label = atom.syntax if atom.kind in {"option", "file", "feature"} and atom.syntax else atom.title
        lines = [f"{'#' * level} {label}"]
    if atom.syntax and atom.kind not in {"option", "file", "feature"}:
        lines.extend(["", "```text", atom.syntax, "```"])
    if atom.body:
        lines.extend(["", atom.body])
    return lines


def render_markdown(document: Document) -> str:
    lines = ["<!-- Generated by Docatoms; do not edit directly. -->", ""]

    def visit(atom: Atom, level: int) -> None:
        lines.extend(_markdown_atom(atom, level))
        lines.append("")
        for child in document.children(atom.tag):
            visit(child, min(level + 1, 6))

    for atom in document.children(None):
        visit(atom, 2)
    return "\n".join(lines).rstrip() + "\n"


def _roff_plain(text: str) -> str:
    text = text.replace("\\", r"\e").replace("~", r"\(ti").replace("-", r"\-")
    if text.startswith((".", "'")):
        text = r"\&" + text
    return text


def _roff_inline(text: str) -> str:
    parts: list[str] = []
    pos = 0
    for match in _INLINE_RE.finditer(text):
        parts.append(_roff_plain(text[pos : match.start()]))
        if match.group(1) is not None:
            parts.extend((r"\fB", _roff_plain(match.group(1)), r"\fR"))
        else:
            parts.extend((r"\fI", _roff_plain(match.group(2)), r"\fR"))
        pos = match.end()
    parts.append(_roff_plain(text[pos:]))
    return "".join(parts)


def _blocks(text: str) -> Iterator[tuple[str, object]]:
    lines = text.splitlines()
    index = 0
    paragraph: list[str] = []

    def take_paragraph() -> tuple[str, object] | None:
        if not paragraph:
            return None
        value = " ".join(line.strip() for line in paragraph)
        paragraph.clear()
        return "paragraph", value

    while index < len(lines):
        line = lines[index]
        if not line.strip():
            block = take_paragraph()
            if block:
                yield block
            index += 1
            continue
        if line.startswith("```"):
            block = take_paragraph()
            if block:
                yield block
            index += 1
            code: list[str] = []
            while index < len(lines) and not lines[index].startswith("```"):
                code.append(lines[index])
                index += 1
            if index == len(lines):
                raise ValueError("unterminated fenced code block")
            yield "code", code
            index += 1
            continue
        if line.startswith("    "):
            block = take_paragraph()
            if block:
                yield block
            code = []
            while index < len(lines) and (lines[index].startswith("    ") or not lines[index]):
                code.append(lines[index][4:] if lines[index] else "")
                index += 1
            yield "code", code
            continue

        numbered = re.match(r"^(\d+)\.\s+(.*)", line)
        if line.startswith("* ") or numbered:
            block = take_paragraph()
            if block:
                yield block
            kind = "numbered" if numbered else "bullet"
            items: list[tuple[str, str]] = []
            while index < len(lines):
                current = lines[index]
                match = re.match(r"^(\d+)\.\s+(.*)", current)
                if kind == "bullet" and current.startswith("* "):
                    marker, value = "", current[2:]
                elif kind == "numbered" and match:
                    marker, value = match.group(1), match.group(2)
                else:
                    break
                index += 1
                continuation: list[str] = []
                while index < len(lines) and lines[index].startswith(("  ", "   ")):
                    continuation.append(lines[index].strip())
                    index += 1
                items.append((marker, " ".join([value, *continuation])))
                if index < len(lines) and not lines[index].strip():
                    index += 1
            yield kind, items
            continue

        paragraph.append(line)
        index += 1

    block = take_paragraph()
    if block:
        yield block


def _roff_body(text: str) -> list[str]:
    lines: list[str] = []
    for kind, value in _blocks(text):
        if kind == "paragraph":
            lines.extend((".PP", _roff_inline(str(value))))
        elif kind == "code":
            lines.extend((".RS 4", ".nf"))
            lines.extend(_roff_plain(line) for line in value)
            lines.extend((".fi", ".RE"))
        else:
            for marker, item in value:
                label = rf'"{marker}."' if kind == "numbered" else r'"\(bu"'
                lines.extend((f".IP {label} 4", _roff_inline(item)))
    return lines


def render_man(document: Document, version: str, section: str = "1") -> str:
    tool = next(atom for atom in document.atoms if atom.kind == "tool")
    manual_name = tool.title.capitalize()
    lines = [
        r'.\" Generated by Docatoms; do not edit directly.',
        f'.TH "{_roff_plain(tool.title.upper())}" "{_roff_plain(section)}" "" '
        f'"{_roff_plain(manual_name)} {_roff_plain(version)}" "{_roff_plain(manual_name)} manual"',
        ".SH NAME",
        _roff_inline(tool.short_help),
        ".SH DESCRIPTION",
        *_roff_body(tool.body),
    ]

    def visit(atom: Atom, depth: int) -> None:
        if atom.kind == "tool":
            return
        if atom.kind in {"option", "file", "feature"}:
            lines.append(".TP")
            lines.append(_roff_inline(f"`{atom.syntax or atom.title}`"))
        else:
            lines.append(f".{('SH' if depth == 0 else 'SS')} {_roff_plain(atom.title.upper() if depth == 0 else atom.title)}")
            if atom.syntax:
                lines.extend((".PP", _roff_inline(f"`{atom.syntax}`")))
        if atom.body:
            body = _roff_body(atom.body)
            if atom.kind in {"option", "file", "feature"} and body[:1] == [".PP"]:
                body = body[1:]
            lines.extend(body)
        for child in document.children(atom.tag):
            visit(child, depth + 1)

    for atom in document.children(None):
        visit(atom, 0)
    return "\n".join(lines).rstrip() + "\n"
